language: php

php:
  - 5.6
  - 7.0
  - hhvm

addons:
  ssh_known_hosts:
  - mijn.svhelloworld.nl
  - 178.62.229.219

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - openssl aes-256-cbc -K $encrypted_412048ce8b71_key -iv $encrypted_412048ce8b71_iv -in deploy-key.pem.enc -out deploy-key.pem -d

before_script:
  - cp .env.travis .env
  - mysql -e 'create database mijn_sv_helloworld_test;'
  - travis_retry composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit

notifications:
  webhooks:
    urls:
      - $GITTER_IM_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

deploy:
  provider: script
  script: ".travis/deploy.sh"
  on:
    branch: master
    php: 7.0
