language: php

php:
  - 7.0
  - 7.1

before_script:
  - gem install mime-types --version "< 3"
  - gem install --conservative mailcatcher
  - mailcatcher
  - cp .env.travis .env
  - mysql -e 'create database mijn_sv_helloworld_test;'
  - travis_retry composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit

notifications:
  webhooks:
    urls:
      - $GITTER_IM_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
